# Uncomment the next line to define a global platform for your project
platform :tvos, '9.2'

target 'VictoryTest' do


  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTAnimation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'BatchedBridge',
      'DevSupport'
  ]
  pod 'RNSVG', path: '../node_modules/react-native-svg'
end

